# -*- coding: utf-8 -*-
"""Calculadora multiusos .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFKj_k8P11xMAYcrQnAKt-Nu_YhDwwI6
"""

import os
from datetime import datetime

# Variable para el historial
historial = []


# la partE MATEMÁTICA
def sumar(a, b): return a + b
def restar(a, b): return a - b
def multiplicar(a, b): return a * b
def potencia(a, b): return a ** b

def modulo(a, b):
  #Division de modulo con validacion de division por cero
  if b == 0: return None
  return a % b

def dividir(a, b):
    # División con validación de división por cero
    if b == 0: return None
    return a / b

def decimal_a_binario(numero):
    if numero == 0: return "0"
    res, n = "", int(numero)
    while n > 0:
        res = str(n % 2) + res
        n //= 2
    return res

def decimal_a_hexadecimal(numero):
    if numero == 0: return "0"
    return hex(int(numero)).split('x')[-1].upper()

def binario_a_decimal(numero):
  #Convierte el numero ingresado a string y luego a int para obtener el valor decimal
  numero = str(numero)
  decimal = int(numero,2)
  return decimal

def hexadecimal_a_decimal(numero):
  #Verifica que lo ingresado sea un string y luego lo vuelve int para obtener el valor decimal
  numero = str(numero)
  decimal = int(numero,16)
  return decimal


# CONVERTIDOR
# Conversiones que ocupamos
def bits_a_bytes(val): return val / 8
def bytes_a_kilobytes(val): return val / 1000
def kilobytes_a_megabytes(val): return val / 1000
def megabytes_a_gigabytes(val): return val / 1000
def gigabytes_a_terabytes(val): return val / 1000
def gigabytes_a_megabytes(val): return val * 1000


# GESTIÓN Y ARCHIVOS
def agregar_al_historial(operacion, num1, num2, resultado):
    global historial
    fecha_hora = datetime.now().strftime("%H:%M:%S")
    # Formato: fecha, operación, resultado
    entrada = f"[{fecha_hora}] {operacion}: {num1} y {num2} = {resultado}"
    historial.append(entrada)
    # Almacenar solo las últimas 10 operaciones
    if len(historial) > 10: historial.pop(0)

def mostrar_historial():
    print("\n" + "HISTORIAL RECIENTE " * 2)
    if not historial:
        print("   > El historial está vacío.")
    else:
        for i, registro in enumerate(historial, 1):
            print(f"  {i}. {registro}")

def guardar_historial_archivo():
    if not os.path.exists("datos"): os.makedirs("datos")
    # Guardar historial en archivo al salir
    with open("datos/historial.txt", "w") as archivo:
        for linea in historial: archivo.write(linea + "\n")

def cargar_historial_archivo():
    global historial
    # Cargar historial al iniciar si existe
    if os.path.exists("datos/historial.txt"):
        with open("datos/historial.txt", "r") as archivo:
            historial.extend([linea.strip() for linea in archivo])
            if len(historial) > 10:
                historial[:] = historial[-10:]

def borrar_historial():
  global historial
  #Dar la opción al usuario de borrar el historial, se repite hasta que se ingrese una opcion valida
  while True:
    try:
      opcion_borrar_historial = int(input("Seguro que quieres borrar el historial?\n1 = SI\n2 = NO\n"))

      if opcion_borrar_historial == 1:
        #Esto limpia el historial de la memoria
        historial.clear()
        if os.path.exists("datos/historial.txt"):
          with open("datos/historial.txt", "w") as archivo:
            archivo.write("")  # Vacía el archivo si es que existe
        print("✅ Historial borrado correctamente.")
        return
      elif opcion_borrar_historial == 2:
        #Esto vuelve al menu principal si se decide que no
        return
        #Se imprime si se elige una opcion invalida con numero entero
      else:
        print("Elige una de las opciones validas")
        #Se imprime si se elige una letra como opcion
    except ValueError:
      print("Error: Debes ingresar un número entero")



def validar_numero(mensaje):
    # Función para verificar entradas
    while True:
        try: return float(input(f"  {mensaje}"))
        except ValueError: print(" X  Error: Ingrese un número válido.")


# MENÚS (ahorita me estoy encargando de arreglar todo esto de menus)
  #Alex: Creo que ya estan arreglados los menus, pero chequen por si acaso
def menu_conversor_unidades():
    print("""
             ╔════════════════════════╗
             ║  CONVERSOR DE DATOS    ║
             ╚════════════════════════╝""")
    print("1. Bits a Bytes\n2. Bytes a KB\n3. KB a MB\n4. MB a GB\n5. GB a MB\n6. GB a TB \n7. Volver")
    op = input("Seleccione: ")
    if op == "7": return
    val = validar_numero("Cantidad: ")
    if op == "1": res, n_op = bits_a_bytes(val), "Bits a B"
    elif op == "2": res, n_op = bytes_a_kilobytes(val), "B a KB"
    elif op == "3": res, n_op = kilobytes_a_megabytes(val), "KB a MB"
    elif op == "4": res, n_op = megabytes_a_gigabytes(val), "MB a GB"
    elif op == "5": res, n_op = gigabytes_a_megabytes(val), "GB a MB"
    elif op == "6": res, n_op = gigabytes_a_terabytes(val), "GB a TB"
    else:
        print("Opción no válida"); return

    print(f" Resultado: {res}")
    agregar_al_historial(n_op, val, "-", res)

def menu_sistemas_numericos():
    print("""
             ╔════════════════════════╗
             ║  SISTEMAS NUMÉRICOS    ║
             ╚════════════════════════╝""")
    print("1. Decimal a Binario\n2. Decimal a Hexadecimal\n3. Binario a Decimal\n4. Hexadecimal a Decimal\n5. Volver")
    op = input("Seleccione: ")
    #Si la opcion es 4 se tiene su propio proceso en el que el valor es un string para realizar la operacion
    if op == "4":
      val = input("Numero hexadecimal: ")
      res, n_op = hexadecimal_a_decimal(val), "Hex a Dec"
      print(f"Resultado: {res}")
      agregar_al_historial(n_op, val, "salida", res)
      return

    elif op == "5": return
    val = int(validar_numero("Número decimal: "))

    if op == "1": res, n_op = decimal_a_binario(val), "Dec a Bin"
    elif op == "2": res, n_op = decimal_a_hexadecimal(val), "Dec a Hex"
    elif op == "3": res, n_op = binario_a_decimal(val), "Bin a Dec"
    else:
        print("Opción no válida"); return

    print(f"Resultado: {res}")
    agregar_al_historial(n_op, val, "salida", res)

def menu_calculadora_basica():
    print("""
             ╔════════════════════════╗
             ║  CALCULADORA BASICA    ║
             ╚════════════════════════╝""")
    print("1. Suma\n2. Resta\n3. Multiplicación\n4. División\n5. Potencia\n6. Modulo \n7. Volver")
    op = input("Seleccione operación: ")

    if op == "7": return

    n1 = validar_numero("Primer número: ")
    n2 = validar_numero("Segundo número: ")

    res = None
    n_op = ""

    if op == "1": res, n_op = sumar(n1, n2), "Suma"
    elif op == "2": res, n_op = restar(n1, n2), "Resta"
    elif op == "3": res, n_op = multiplicar(n1, n2), "Mult"
    elif op == "4":
        res = dividir(n1, n2)
        n_op = "Div"
        if res is None: print(" X  Error: División por cero.")
    elif op == "5": res, n_op = potencia(n1, n2), "Pot"
    elif op == "6": res, n_op = modulo(n1 , n2), "Modulo"
    else:
        print(" X  Opción no válida.")
        return

    if res is not None:
        print(f" Resultado: {res}")
        agregar_al_historial(n_op, n1, n2, res)

def main():
    cargar_historial_archivo()
    while True:
        # Menú
        print(r"""
  ++ ______________________________________________++
     ||                                              ||
     ||   _____   _   _    ____   _ _     __         ||
     ||  | ____| | | | |  / ___| |  _  \ | |         ||
     ||  | |     | | | | |  _    | | | | | |         ||
     ||  | |___  | |_| | | |_| | | |_| | | |___      ||
     ||  |_____|  \___/   \____| |____/  |_____|     ||
     ||                                              ||
     ||               Calculador multiusos           ||
     ||                te sirve pa'todo              ||
     ||                                              ||
     ___________________________________________________
     """)

        print("1. Calculadora Básica\n2. Conversor de Datos\n3. Sistemas Numéricos\n4. Historial\n5. Borrar Historial \n6. Salir")
        opcion = input("\nOpción: ")
        if opcion == "1": menu_calculadora_basica()
        elif opcion == "2": menu_conversor_unidades()
        elif opcion == "3": menu_sistemas_numericos()
        elif opcion == "4": mostrar_historial()
        elif opcion == "5": borrar_historial()
        elif opcion == "6":
            guardar_historial_archivo()
            print("Chau!")
            break
        else:
            print(" Opción no válida.")

if __name__ == "__main__":
    main()